import { subHours, formatISO } from 'date-fns';
import type { Article } from '../types/article';

export type RawArticle = Omit<Article, 'score' | 'signalLevel' | 'whyFlagged'>;

const now = new Date();

export const mockArticles: RawArticle[] = [
  {
    id: '1',
    title: 'Iran accelerates uranium enrichment at Natanz facility',
    source: 'Reuters',
    author: 'John Doe',
    publishedAt: formatISO(subHours(now, 1)),
    url: '#',
    description: 'Fresh IAEA reports indicate a significant increase in 60% enriched uranium stockpiles.',
    content: 'Full article content would go here...',
    matchedKeywords: ['uranium', 'enrichment', 'Natanz', 'IAEA'],
    aiSummary: 'Iran reported to have increased highly enriched uranium production, nearing weapons-grade threshold according to IAEA monitors.',
    category: 'Nuclear',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.95,
    trajectory: 'rising',
    location: { lat: 33.72, lng: 51.91, label: 'Natanz' }
  },
  {
    id: '2',
    title: 'Drone strike reported near military base in Isfahan',
    source: 'Al Jazeera',
    author: 'Jane Smith',
    publishedAt: formatISO(subHours(now, 2)),
    url: '#',
    description: 'Explosions heard near a major airbase in central Iran; air defenses activated.',
    content: 'Full article content would go here...',
    matchedKeywords: ['drone', 'strike', 'Isfahan', 'military base'],
    aiSummary: 'Unidentified drone strike targeted a military facility in Isfahan, causing localized damage. Air defenses successfully intercepted minor threats.',
    category: 'Conflict',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.88,
    trajectory: 'rising',
    location: { lat: 32.65, lng: 51.67, label: 'Isfahan' }
  },
  {
    id: '3',
    title: 'Oil tanker seized by Iranian naval forces in Strait of Hormuz',
    source: 'Bloomberg',
    author: null,
    publishedAt: formatISO(subHours(now, 4)),
    url: '#',
    description: 'A Marshall Islands-flagged oil tanker was diverted to Iranian territorial waters amid escalating maritime tensions.',
    content: 'Full article content would go here...',
    matchedKeywords: ['Strait of Hormuz', 'oil tanker', 'seized', 'naval'],
    aiSummary: 'Iranian forces seized a commercial oil tanker in the critical Strait of Hormuz chokepoint, citing maritime violations.',
    category: 'Maritime/Energy',
    duplicateGroup: 'group-a',
    sentiment: 'negative',
    reliability: 0.92,
    trajectory: 'stable',
    location: { lat: 26.56, lng: 56.25, label: 'Strait of Hormuz' }
  },
  {
    id: '4',
    title: 'IRGC Satellite Launch Confirmed; US Intelligence Monitoring',
    source: 'WSJ',
    author: 'Military Desk',
    publishedAt: formatISO(subHours(now, 0.5)),
    url: '#',
    description: 'The IRGC Space Command successfully placed a tactical imaging satellite into low earth orbit.',
    content: 'Full article content...',
    matchedKeywords: ['IRGC', 'Satellite', 'monitoring', 'space'],
    aiSummary: 'New satellite launch by IRGC Space Command suggests enhanced regional surveillance capabilities. US Space Command currently tracking trajectory.',
    category: 'Intelligence',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.90,
    trajectory: 'rising',
    location: { lat: 35.22, lng: 53.92, label: 'Semnan Space Center' }
  },
  {
    id: '5',
    title: 'Tehran Stock Exchange Plummets as Sanction Fears Mount',
    source: 'Euronews',
    author: null,
    publishedAt: formatISO(subHours(now, 6)),
    url: '#',
    description: 'The TEDPIX index dropped 4% in early trading following reports of a new EU-US joint sanctions package.',
    content: 'Full article content...',
    matchedKeywords: ['sanctions', 'Tehran Stock Exchange', 'economy'],
    aiSummary: 'Economic instability in Tehran deepens as markets react to the threat of broader international trade restrictions.',
    category: 'Economy',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.85,
    trajectory: 'falling',
    location: { lat: 35.68, lng: 51.38, label: 'Tehran' }
  },
  {
    id: '6',
    title: 'Strategic Coordination Meeting in Damascus: IRGC & Hezbollah',
    source: 'Haaretz',
    author: 'Intelligence Analyst',
    publishedAt: formatISO(subHours(now, 3)),
    url: '#',
    description: 'High-ranking IRGC Quds Force commanders met with Hezbollah leadership to discuss regional defense postures.',
    content: 'Full article content...',
    matchedKeywords: ['Damascus', 'IRGC', 'Hezbollah', 'Quds Force'],
    aiSummary: 'Intelligence confirms a high-level coordination meeting between Quds Force and Hezbollah in Damascus, likely focusing on Northern-front readiness.',
    category: 'Conflict',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.82,
    trajectory: 'rising',
    location: { lat: 33.51, lng: 36.29, label: 'Damascus' }
  },
  {
    id: '7',
    title: 'Cyber-Attack Targets Iranian Port Infrastructure',
    source: 'Wired',
    author: 'Cyber Security Analyst',
    publishedAt: formatISO(subHours(now, 8)),
    url: '#',
    description: 'Operational technology at Bandar Abbas port suffered a significant malfunction following a suspected state-sponsored cyber-attack.',
    content: 'Full article content...',
    matchedKeywords: ['cyber-attack', 'Bandar Abbas', 'infrastructure'],
    aiSummary: 'Logistics disruptions at Bandar Abbas reported after a sophisticated malware strain targeted port loading systems.',
    category: 'Cyber',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.88,
    trajectory: 'rising',
    location: { lat: 27.18, lng: 56.28, label: 'Bandar Abbas' }
  },
  {
    id: '8',
    title: 'Saudi-Iranian Backchannel Talks Continue in Baghdad',
    source: 'Al Monitor',
    author: null,
    publishedAt: formatISO(subHours(now, 10)),
    url: '#',
    description: 'Delegates from Riyadh and Tehran arrived in Baghdad for the fifth round of security normalization talks.',
    content: 'Full article content...',
    matchedKeywords: ['Baghdad', 'talks', 'Saudi Arabia'],
    aiSummary: 'Normalization efforts between regional rivals continue with Iraqi mediation, despite ongoing tensions on the ground.',
    category: 'Diplomacy',
    duplicateGroup: null,
    sentiment: 'positive',
    reliability: 0.80,
    trajectory: 'stable',
    location: { lat: 33.31, lng: 44.36, label: 'Baghdad' }
  },
  {
    id: '9',
    title: 'B-52 Stratofortress Deployment to Al-Udeid Confirmed',
    source: 'CNN',
    author: 'Pentagon Correspondent',
    publishedAt: formatISO(subHours(now, 12)),
    url: '#',
    description: 'CENTCOM confirms the arrival of heavy bombers to the regional airbase as a "deterrence measure."',
    content: 'Full article content...',
    matchedKeywords: ['B-52', 'Al-Udeid', 'deployment', 'CENTCOM'],
    aiSummary: 'US Air Force reinforces regional presence with long-range bombers, signaling a readiness posture amid Iranian activity.',
    category: 'Conflict',
    duplicateGroup: null,
    sentiment: 'neutral',
    reliability: 0.98,
    trajectory: 'rising',
    location: { lat: 25.12, lng: 51.21, label: 'Al-Udeid Air Base' }
  },
  {
    id: '10',
    title: 'Protests Erupt in Sistan and Baluchestan Over Water Scarcity',
    source: 'BBC News',
    author: null,
    publishedAt: formatISO(subHours(now, 18)),
    url: '#',
    description: 'Security forces deployed to Zahedan after demonstrations turned violent in the border province.',
    content: 'Full article content...',
    matchedKeywords: ['Zahedan', 'protests', 'security forces'],
    aiSummary: 'Internal instability rises in Iran\'s southeastern provinces as environmental stressors trigger widespread social unrest.',
    category: 'Internal Security',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.84,
    trajectory: 'rising',
    location: { lat: 29.49, lng: 60.86, label: 'Zahedan' }
  },
  {
    id: '11',
    title: 'New Gas Field Discovered in Caspian Territorial Waters',
    source: 'OilPrice.com',
    author: null,
    publishedAt: formatISO(subHours(now, 24)),
    url: '#',
    description: 'Iranian energy ministry announces a significant new offshore natural gas find near the maritime boundary.',
    content: 'Full article content...',
    matchedKeywords: ['gas field', 'Caspian', 'energy ministry'],
    aiSummary: 'Long-term energy prospects for Tehran improve with a major offshore discovery, potentially shifting regional gas dynamics.',
    category: 'Maritime/Energy',
    duplicateGroup: null,
    sentiment: 'positive',
    reliability: 0.82,
    trajectory: 'stable',
    location: { lat: 37.47, lng: 50.45, label: 'Caspian Sea' }
  },
  {
    id: '12',
    title: 'Advanced Air Defense Drills Conducted Near Bushehr',
    source: 'Tasnim News',
    author: null,
    publishedAt: formatISO(subHours(now, 1.5)),
    url: '#',
    description: 'The Iranian Air Force tested the "Bavar-373" system in a simulated environment protecting critical energy infrastructure.',
    content: 'Full article content...',
    matchedKeywords: ['Bushehr', 'Air Defense', 'Bavar-373'],
    aiSummary: 'Iran showcases indigenous surface-to-air missile capabilities during integrated drills near the Bushehr nuclear plant.',
    category: 'Nuclear',
    duplicateGroup: null,
    sentiment: 'neutral',
    reliability: 0.75,
    trajectory: 'rising',
    location: { lat: 28.82, lng: 50.88, label: 'Bushehr' }
  },
  {
    id: '13',
    title: 'Interpol Red Notice Issued for Former Intelligence Officer',
    source: 'The Guardian',
    author: null,
    publishedAt: formatISO(subHours(now, 14)),
    url: '#',
    description: 'International warrant follows the defection of a senior official suspected of leaking highly classified documents.',
    content: 'Full article content...',
    matchedKeywords: ['Interpol', 'Intelligence', 'leaking'],
    aiSummary: 'A major security breach in Iran\'s internal apparatus comes to light as a high-ranking officer defects to a neighboring country.',
    category: 'Intelligence',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.81,
    trajectory: 'rising',
    location: { lat: 35.68, lng: 51.38, label: 'Tehran' }
  },
  {
    id: '14',
    title: 'G7 Leaders Issue Stern Warning Over Strategic Cooperation with Moscow',
    source: 'Politico',
    author: 'EU Correspondent',
    publishedAt: formatISO(subHours(now, 5)),
    url: '#',
    description: 'Joint communiqué highlights "severe consequences" if Tehran provides tactical ballistic missiles to Russian forces.',
    content: 'Full article content...',
    matchedKeywords: ['G7', 'Moscow', 'missiles'],
    aiSummary: 'Western powers sharpen their stance on Iran-Russia defense cooperation, threatening further economic isolation.',
    category: 'Diplomacy',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.94,
    trajectory: 'rising',
    location: { lat: 52.52, lng: 13.40, label: 'Berlin (G7 HQ)' }
  },
  {
    id: '15',
    title: 'Unusual Freight Traffic Observed at Imam Khomeini International Airport',
    source: 'OSINT Weekly',
    author: 'Satellite Analyst',
    publishedAt: formatISO(subHours(now, 2.5)),
    url: '#',
    description: 'Flight tracking and satellite imagery show a surge in Russian-operated heavy cargo flights arriving at night.',
    content: 'Full article content...',
    matchedKeywords: ['OSINT', 'Airport', 'cargo flights'],
    aiSummary: 'Heightened logistical activity at Tehran\'s main airport suggests an ongoing transfer of sensitive materials or military hardware.',
    category: 'Conflict',
    duplicateGroup: null,
    sentiment: 'negative',
    reliability: 0.78,
    trajectory: 'rising',
    location: { lat: 35.41, lng: 51.15, label: 'Imam Khomeini Airport' }
  }
];
